### ISSUE TITLE
make a better splash page

### ISSUE THREAD

**Issue by balmas** [PerseusDL/perseus_nemo_ui#3]
we should replace the "Welcome to Nemo!" default splash page with text which describes the ongoing Perseus/Perseids CTS transition effort.

**Comment by lcerrato** [comment]
A blurb I wrote to a user:

We haven't made an official, unified announcement of the plans for the texts in the Perseus context specifically or addressed this work outside of white papers and other specialized presentations and publications.

The main impetus of the effort is bringing the texts into CTS (http://www.homermultitext.org/hmt-doc/cite/texts/cts.html) and EpiDoc TEI (http://www.stoa.org/epidoc/gl/latest/index.html) compliance in the context of the efforts on Perseids (http://www.perseids.org), which is is a collaborative editing platform that offers a suite of services for things like treebanking, annotation, transcriptions, commentaries, text alignments, and other forms of text reuse. This is a grant-funded initiative based within Perseus and as it is user-driven, it provides numerous exciting opportunities for user contributions not just in classics, but throughout the humanities.

In terms of how this impacts Perseus 4.0 (the Perseus Digital Library you access via the WWW):

1) In the short term, it won't. We are committed to maintaining the site "as is" as best we can given limited system administration support and staffing, 10+ year old code, architecture challenges, and various legacy issues. We are not planning on removing the current version of Perseus but we do not expect any major revisions to what you see now.

2) In the long(er) term, we are looking at a distributed model of publication, where parts of Perseus or Perseus tools and services may be offered in different interfaces or within other projects. We hope to present the CTS-EpiDoc versions of texts in a demonstration reading environment but we don't envision this as a one to one replacement of Perseus 4.0. We recognize that we cannot instantly replace all of the Perseus features given that we simply do not know what kind of resources we will have. We certainly plan to continue to build upon this work in the context of the larger digital classics community.

Hopefully, the new text work will be an impetus for others to build on the work and create custom environments as they see examples of the texts and other data being reused in new ways via Perseids and other projects.

**Comment by balmas** [comment]
Tim suggests: 

"Welcome to the Perseus Project, hosted by Nemo. Nemo is an extension for Flask and provides a User Interface layer for a CTS Repository. We at Perseus have been in the process of bringing our texts into CTS (http://www.homermultitext.org/hmt-doc/cite/texts/cts.html) and EpiDoc TEI (http://www.stoa.org/epidoc/gl/latest/index.html) compliance. Hopefully, the new text work will be an impetus for others to build on the work and create custom environments as they see examples of the texts and other data being reused in new ways.

In the longer term, we are looking at a distributed model of publication, where parts of Perseus or Perseus tools and services will be hosted using the CapiTainS tool suite (http://capitains.github.io/). We plan to continue to build upon this work in the context of the larger digital classics community. "

**Comment by lcerrato** [comment]
Honest question, are we presuming the audience for this knows what Flask is? I would also expand on the CTS and TEI definitions. We have CTS language in the catalog definitions. I would also put links at the end, as most people don't follow them.

If you see the audience solely as power users, then this works. If I wind up directing people to these tools via other inquiries, I think there needs to be a little more basic explanation. Maybe that's not for this pass.

I also find it odd to call it the Perseus Project. Both because we don't use that regularly and Perseus is more than texts, so there is no 1 to 1 equivalence here. I would frame it more as a subset of materials, perhaps in an experimental format?

**Comment by balmas** [comment]
I might suggest the following amalgamation of what you both have provided. Would be good to get feedback from @PonteIneptique too

Welcome to the Perseus Digital Library's CapiTainS environment.  

Perseus is bringing its primary source texts into [CTS](http://www.homermultitext.org/hmt-doc/cite/texts/cts.html) and [EpiDoc TEI](http://www.stoa.org/epidoc/gl/latest/index.html) compliance in the context of the efforts on the Perseids Project (http://www.perseids.org).  This is an ongoing effort and, as it is user-driven, it provides numerous exciting opportunities for user contributions not just in classics, but throughout the humanities.  If you are interested in participating in the text conversion efforts, please email webmaster 'at' perseus.tufts.edu.

[CapiTainS](http://capitains.github.io/) is a suite of tools and guidelines for the CTS standards.  The user interface provided here is an extension of the [Nemo Flask application](http://flask-capitains-nemo.readthedocs.org/) and the texts are served by the [Nautilus CTS provider](http://capitains-nautilus.readthedocs.io/en/latest/).  Texts are updated directly from the PerseusDL canonical [github](https://github.com/PerseusDL) repositories as they pass tests in the [Hook Continuous Integration environment](https://github.com/Capitains/Hook).

**Comment by TDBuck** [comment]
@balmas +1 on the combined version.

**Comment by lcerrato** [comment]
I would like to be able to convey what this means to average user because I expect that I will be doing so anyhow. 

Not sure of about the text conversion call in this context, though. I have not yet updated the instructions in any meaningful way and I think that should be separate. (We also have calls already ongoing in the OGL context and Greek OCR context, correct?)

**Comment by balmas** [comment]
@lcerrato That's all fine with me.

**Comment by lcerrato** [comment]
To clarify — we cross posted a bit.
My follow up questions to reading this above, would be
- Why CTS?
- Is Perseus going away or being replaced?
- How can I offer constructive feedback?

**Comment by balmas** [comment]
I agree those are all needed additions.

as to "why cts", feel free to take from this excerpt from my infrastructure blog post
"The Center for Hellenic Studies’ Homer Multitext project did pioneering work in developing the CITE architecture to define machine-actionable, technology independent standards for identifying, citing and retrieving texts and text-related data objects. This has given us a solid framework within which to begin addressing some of these needs, especially when it comes to working with canonical texts and citations to them. Implementing the Canonical Text Services (CTS) URN specification component of CITE allows us to produce a semantically meaningful identifier which represents the position of a text in the hierarchy in which it is traditionally cited. This same identifier scheme can also be used to cite into the text at the passage level, within a specific version or instance of that text, or within the notional work the text represents. So, for example, while a traditional reference to Book 1 Line 1 in Homer’s Iliad as cited in literature might be “Hom Il. 1.1”, this can be represented as urn:cts:greekLit:tlg0012.tlg001:1.1, as a citation to the notional work The Iliad, or as urn:cts:greekLit:tlg0012.tlg001.perseus-grc1:1.1 in the specific ‘perseus-grc1’ edition of this work. (The CTS specification and the Perseus Catalog documentation explain these components more fully, but briefly, the other components of the URN here are a namespace, greekLit, a textgroup identifier, tlg0012, for the group of texts attributed to the author Homer, a work identifier, tlg001, for the work The Iliad and a passage identifier, 1.1)."

For "is Perseus going away" i think your description in the first comment on this item is great

For "how to offer constructive feedback" I think it's a question of how specific you want to be here, knowing that people are likely not to follow instructions anyway.  This was generally my thinking with just referencing webmaster, but am happy to suggest more concrete alternatives (e.g. if you want to know why a text isn't here do X, if you want to comment on how the text is presented in the interface do Y, etc.)

**Comment by lcerrato** [comment]
Yes, I was just looking at the Catalog language on why CTS. Was going to suggest something a little fuller than that but not highly technical.
e.g." CTS offers several advantages ... will allow for more refined citation and text retrieval by offering precision in cross referencing..." 

This is because the average user (if they are indeed going to be referred here) has not encountered any publications or discussions of this via official channels, except in Perseus Updates.

Re feedback, I was going to offer step by step instructions on creating issues with the option of webmaster contact. Was thinking about whether we want to make a distinction between suggested UI improvements or follow up questions on what this means for Perseus 4 users. 

I think that if we use the webmaster, I would be left to creating issues here out of those emails and then managing correspondence. That doesn't seem to be efficient but it may not be avoidable.

But then, I'm not sure all users want the conversations on GitHub, either.

**Comment by lcerrato** [comment]
Let's see what we have now and I am happy to build upon it in a separate pass.

**Comment by balmas** [comment]
sorry, not sure I understand. do you want me to synthesize again based upon the most recent comments? Or are you making a pass on it in a separate doc?

**Comment by lcerrato** [comment]
I would like to either work on the published v 1 or an editable version elsewhere.

**Comment by PonteIneptique** [comment]
Just a little comment : wouldn't it be important to cite Leipzig-Tufts joint effort on this suite ?

**Comment by lcerrato** [comment]
@PonteIneptique Yes! 

Discussion has moved off line due to the difficulty of trying to edit in this format.

Please work with @TDBuck to add more information and refine what is there.
